
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    test: startup
  name: startup-exec
  namespace: advanced-tp3
spec:
  selector:
    matchLabels:
      test: startup
  template:
    metadata:
      labels:
        test: startup
    spec:
      containers:
        - name: startup
          image: registry.k8s.io/busybox
          args:
            - /bin/sh
            - -c
            - sleep 15; touch /tmp/healthy; sleep 600
          livenessProbe:
            exec:
              command:
                - cat
                - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            exec:
              command:
                - cat
                - /tmp/healthy
            failureThreshold: 1
            periodSeconds: 20