apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-daemonset
  namespace: advanced-tp4
  labels:
    app: fluentd-daemonset
spec:
  selector:
    matchLabels:
      app: fluentd-daemonset
  template:
    metadata:
      labels:
        app: fluentd-daemonset
    spec:
      priorityClassName: system-node-critical
      containers:
        - name: fluentd
          image: fluent/fluentd:v1.17
          env:
            - name: FLUENTD_ARGS
              value: "--no-supervisor"
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: critical-priority-quota
  namespace: advanced-tp4
spec:
  hard:
    pods: 1G
  scopeSelector:
    matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values:
          - system-node-critical
          - system-cluster-critical