apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lifecycle
spec:
  selector:
    matchLabels:
      test: lifecycle
  template:
    metadata:
      labels:
        test: lifecycle
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80