apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: emoji
  namespace: linkerd-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: voting
  namespace: linkerd-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: linkerd-demo
---
apiVersion: v1
kind: Service
metadata:
  name: emoji-svc
  namespace: linkerd-demo
spec:
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: prom
      port: 8801
      targetPort: 8801
  selector:
    app: emoji-svc
---
apiVersion: v1
kind: Service
metadata:
  name: voting-svc
  namespace: linkerd-demo
spec:
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: prom
      port: 8801
      targetPort: 8801
  selector:
    app: voting-svc
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: linkerd-demo
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: web-svc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: emoji
    app.kubernetes.io/part-of: linkerd-demo
    app.kubernetes.io/version: v11
  name: emoji
  namespace: linkerd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emoji-svc
      version: v11
  template:
    metadata:
      labels:
        app: emoji-svc
        version: v11
    spec:
      containers:
        - env:
            - name: GRPC_PORT
              value: "8080"
            - name: PROM_PORT
              value: "8801"
          image: docker.l5d.io/buoyantio/emojivoto-emoji-svc:v11
          name: emoji-svc
          ports:
            - containerPort: 8080
              name: grpc
            - containerPort: 8801
              name: prom
          resources:
            requests:
              cpu: 100m
      serviceAccountName: emoji
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: vote-bot
    app.kubernetes.io/part-of: linkerd-demo
    app.kubernetes.io/version: v11
  name: vote-bot
  namespace: linkerd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-bot
      version: v11
  template:
    metadata:
      labels:
        app: vote-bot
        version: v11
    spec:
      containers:
        - command:
            - emojivoto-vote-bot
          env:
            - name: WEB_HOST
              value: web-svc.linkerd-demo:80
          image: docker.l5d.io/buoyantio/emojivoto-web:v11
          name: vote-bot
          resources:
            requests:
              cpu: 10m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: voting
    app.kubernetes.io/part-of: linkerd-demo
    app.kubernetes.io/version: v11
  name: voting
  namespace: linkerd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-svc
      version: v11
  template:
    metadata:
      labels:
        app: voting-svc
        version: v11
    spec:
      containers:
        - env:
            - name: GRPC_PORT
              value: "8080"
            - name: PROM_PORT
              value: "8801"
          image: docker.l5d.io/buoyantio/emojivoto-voting-svc:v11
          name: voting-svc
          ports:
            - containerPort: 8080
              name: grpc
            - containerPort: 8801
              name: prom
          resources:
            requests:
              cpu: 100m
      serviceAccountName: voting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: linkerd-demo
    app.kubernetes.io/version: v11
  name: web
  namespace: linkerd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-svc
      version: v11
  template:
    metadata:
      labels:
        app: web-svc
        version: v11
    spec:
      containers:
        - env:
            - name: WEB_PORT
              value: "8080"
            - name: EMOJISVC_HOST
              value: emoji-svc.linkerd-demo:8080
            - name: VOTINGSVC_HOST
              value: voting-svc.linkerd-demo:8080
            - name: INDEX_BUNDLE
              value: dist/index_bundle.js
          image: docker.l5d.io/buoyantio/emojivoto-web:v11
          name: web-svc
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 100m
      serviceAccountName: web