apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    test: liveness-readiness
  name: readiness-exec
  namespace: advanced-tp3
spec:
  replicas: 1
  selector:
    matchLabels:
      test: liveness-readiness
  template:
    metadata:
      labels:
        test: liveness-readiness
    spec:
      containers:
        - image: registry.k8s.io/e2e-test-images/agnhost:2.40
          name: readiness
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    test: liveness-readiness
  name: liveness-exec
  namespace: advanced-tp3
spec:
  replicas: 1
  selector:
    matchLabels:
      test: liveness-readiness
  template:
    metadata:
      labels:
        test: liveness-readiness
    spec:
      containers:
        - image: registry.k8s.io/e2e-test-images/agnhost:2.40
          name: liveness
          args:
            - liveness
---
apiVersion: v1
kind: Service
metadata:
  name: service-liveness-readiness
spec:
  ports:
    - port: 80
  selector:
    test: liveness-readiness