apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sidecar
spec:
  selector:
    matchLabels:
      test: sidecar
  template:
    metadata:
      labels:
        test: sidecar
    spec:
      containers:
        - name: nginx
          image: nginx:1.27.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share/nginx/html
      volumes:
        - name: shared-data
          emptyDir: {}