apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sidecar
spec:
  selector:
    matchLabels:
      test: sidecar
  template:
    metadata:
      labels:
        test: sidecar
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share/nginx/html
        - name: content-generator
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              while true; do
                echo "Date et heure: $(date)" > /usr/share/nginx/html/index.html;
                sleep 1;
              done
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share/nginx/html
      volumes:
        - name: shared-data
          emptyDir: {}