apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: advanced-tp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.27.2
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              port: http
          readinessProbe:
            httpGet:
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: advanced-tp2
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: nginx