---
apiVersion: v1
kind: Service
metadata:
  name: watchdog
  namespace: watchdog
spec:
  selector:
    app: watchdog
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: watchdog
  name: watchdog
  namespace: watchdog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchdog
  template:
    metadata:
      labels:
        app: watchdog
    spec:
      containers:
      - name: watchdog
        image: europe-west1-docker.pkg.dev/qsh-learning-k8s-advanced/qsh-learning/watchdog/srv:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
        env:
          - name: PYTHONPATH
            value: $PYTHONPATH:/
        volumeMounts:
          - mountPath: /watchdog/certs
            name: watchdog-certs
      volumes:
      - name: watchdog-certs
        secret:
          secretName: watchdog-certs

