apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app: watchdog
  name: mutating-webhook-configuration
  namespace: watchdog

webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUY5VENDQTkyZ0F3SUJBZ0lVRGFrY2s1aVBSMVh3WGFuYXNlQnp3ZnQyODIwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZZ3hDekFKQmdOVkJBWVRBa1pTTVF3d0NnWURWUVFJREFOT1FWRXhFekFSQmdOVkJBY01Da3hGSUVoQgpTVXhNUVU0eEVEQU9CZ05WQkFvTUJ6UlRTQ0JUUVZNeERqQU1CZ05WQkFzTUJVbE9SbEpCTVE4d0RRWURWUVFECkRBWTBjMmd1Wm5JeEl6QWhCZ2txaGtpRzl3MEJDUUVXRkdsdVpuSmhjM1IxWTNSMWNtVkFOSE5vTG1aeU1DQVgKRFRJME1UQXdPREV4TkRNMU1Wb1lEekl3TnpReE1EQTJNVEUwTXpVeFdqQ0JpREVMTUFrR0ExVUVCaE1DUmxJeApEREFLQmdOVkJBZ01BMDVCVVRFVE1CRUdBMVVFQnd3S1RFVWdTRUZKVEV4QlRqRVFNQTRHQTFVRUNnd0hORk5JCklGTkJVekVPTUF3R0ExVUVDd3dGU1U1R1VrRXhEekFOQmdOVkJBTU1CalJ6YUM1bWNqRWpNQ0VHQ1NxR1NJYjMKRFFFSkFSWVVhVzVtY21GemRIVmpkSFZ5WlVBMGMyZ3Vabkl3Z2dJaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQwpEd0F3Z2dJS0FvSUNBUUNwdDUyS1cvMm5GV2JUOTJGLzJhUS9kRVY4K1J4Y29sNTJRSGcxeW1XREp2MFhNSE9xCjI3L1FVS2lGUkNNVEE4eXRkQlZSSGZLeEs5eW9BcU1lZWtVMDMvWThXRys5Z1ZWRkdnN211T3IvM05WYWJSMHAKY0x2Vm5YQmhIN1pwUC9CalZXdWpPTm5qL3g4V2p5eEJTWUdXc3ZHaDdTaWNSZ3ZhbHZaWXFvY1p4cHB2VXVtTAoxZXpZZVlTVitRL0JPc0pYd1lGaXVndzcxOExTdkZpSjVGT2o3ekhpYm9pbWtrTWY2RmhmREFock5Jc0hBRm5NCmNsSVRrSVZVSks4dWl5Ly8zWURFMkVkUjVoWm9OUFRPL0RORjFFZFdtWUR1RzZmbVFYcnBtRDcwODVWWGFveVkKRWpVWnh4Q2JhYnpPYWZGY012ejgrSy9qOFNmc1J6dzFRQlkvczdza3JpcEJLOFAxQWZRdWxGRnQ5bXk0K3NrWgp2dTZIM3pJVjRkdFpXTkdWcmRRaDFQVjU2MUovNHE2RzNPdTA5Wmxwa3BkVEhsRTNqSkJVQWJnRzNQRVB5T05DCnlrWWtML09jUlBwdGN5dFJNV3c4Vm1vRHNVbk92REpIeUsybEdGZElGZzZkbEZZWWthWFZTU210V0FTdUF1YWUKUm1uRG8zOTJmTno4OSthdS95SGcxbCtOaU54K1NHZzN1cDUvN0JjVThTS2JsMUE1SXYvVFd2dGlEL05ici9MaQpPU2REMUpSVE9US0wwYVgzWTF1MkxtRmVFSXoxNlh5NDdIdVcyYnlSUU5HQWswb3FRYVo4cW1xYmZ0aDEraGFICk1yNlI4SVJjUkNxdlZFSEIyZTNkdEhQakRSODVsNWhwdWgrS0M4U01KSXJRbTlUdDVMektwelpvMlFJREFRQUIKbzFNd1VUQWRCZ05WSFE0RUZnUVVzQmR1UGFOWWh6ZXk4cXVWcWdNcDQ2L2M0K3N3SHdZRFZSMGpCQmd3Rm9BVQpzQmR1UGFOWWh6ZXk4cXVWcWdNcDQ2L2M0K3N3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCCkFRc0ZBQU9DQWdFQVBlNUZKM3AveVFVVlFPa3dzWFEySWppcFE2cnFKTXJaTG5Ed0ZFSzhWaklhZks3bGl3amoKRXlHbjNmTFF3dkZ1RFR4S0VaMEJ0Wm43dFcrU3VHcEVrYmhIcXA5aHRuWTBvWGtZWWFGQ3J5ejJ5NHJYaWxsNgp3OUdNYXpYSWtTL2RaZCtSS3llOHVDTVh2dlhCa2FsTFlXWmtiOG9RcEZxMEFtVGhGdUZ3Ky8xaHB0Y2xTSFBFCjJOVlNuTld6N0xSelZHQ3VQU2tHSEpUK1lJUXlxb215TjFZeUFDWDdjekFLTHhRczBrekdWYlFxNXJxSkZjc3cKU2JZNDdzUDZIWFVuMHdSdmFENkZYcUJoZ0JkTlRuWE5oaHBtUFdyUWFBTUozSURVYmxzbDgvS0p3Kzhab2d2bQpPcDJJZFc1bnZGV21ZMndjbnNrU0dNaDUzamEvbE9uQ1FWM2ZuRGVqb0VVbFk0ZmtFT3kzY3R4UDdNUDZWa0F4Ckl3Nkdya254a3pqOXNiZzN2THNKT3VDbENWclovcXg1cS8xRkhqV3RMQ28yL0t3MnIwbzkrQ0luemsxamNKaDAKcGlJYTRKTzJzeTByNlEyZm9OQ1BMVWhVMzhHbVlIUzFFdENFbkZBTHl0RFYwdDVlelJaZHE4cmZJWk12cE1HdAowMWNlSDNRNGlOa2YxMXBVaVBENlFvMlFPbEdxQlRlbXlWVXFrM2twRW5IdEVWOEVNcHU1SDM5cStmbXZKSytBCkFVNTBxNWpuZkgwTmhMSUlFaUJHZjdjV0hmdG5KZFlKR3A4WDF6TXpXUUNUVXM1UmFuQVpZUTFvY1crSzBxamsKVSs1eHJzWnc4TG9uWU5tbGVKMmpGcm1GR1g0a3BsOURHRlFHQjBzV0lIcFF6Q0JORzIxc1Q2RT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: watchdog
        namespace: watchdog
        path: /mutate/pod
        port: 443
    failurePolicy: Ignore
    matchPolicy: Exact
    name: watchdog.watchdog.svc.cluster.local
    namespaceSelector:
      matchExpressions:
        - key: customer
          operator: In
          values:
            - formation
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
        scope: 'Namespaced'
    sideEffects: None
    timeoutSeconds: 5
